name: ci
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['8.0x']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup        
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - name: Restore
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-restore  --diag logs.txt
        
      - name: Docker
        uses: ./.github/actions/docker_actions
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         token: ${{ secrets.DOCKERHUB_TOKEN }}
