name: ci
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Generate and push Docker image
        uses: ./.github/actions
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          token: ${{ secrets.DOCKERHUB_TOKEN }}
